spring.application.name=hipertrofia
# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hipertrofia_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Configurações do JPA/Hibernate
# "update" faz o Spring criar as tabelas no banco automaticamente baseado no nosso código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta onde a API vai rodar
server.port=8080